---
- hosts: zkhosts
  become: true
  connection: ssh
  vars:
    - brokerid: "{{ inventory_hostname | regex_search('(kisu-zk0[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^kisu-zk0', '') }}"
    - zookeeperinfo: kisu-zk01.foo.bar:2181,kisu-zk02.foo.bar:2181,kisu-zk03.foo.bar:2181/kafka2
    - dir_path: /data/kafka2-logs
  roles:
    - common
    - kafka