---
- hosts: kafkahosts
  become: true
  connection: ssh
  vars:
    - zookeeperinfo: kisu-zk01.foo.bar:2181,kisu-zk02.foo.bar:2181,kisu-zk03.foo.bar:2181/kafka1
    - dir_path: /data/kafka1-logs
  roles:
    - common
    - kafka