brokerid: "{{ inventory_hostname | regex_search('(kisu-kafka0[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^kisu-kafka0', '') }}"
zookeeperinfo: kisu-zk01.foo.bar:2181,kisu-zk02.foo.bar:2181,kisu-zk03.foo.bar:2181
dir_path: /data/kafka-logs